const char daftarisiquran[] PROGMEM = R"=====(Al Fatihah
Al Baqarah
Ali Imran
An Nisa
Al Ma'idah
Al An'am
Al-A'raf
Al-Anfal
At-Taubah
Yunus
Hud
Yusuf
Ar-Ra'd
Ibrahim
Al-Hijr
An-Nahl
Al-Isra'
Al-Kahf
Maryam
Ta Ha
Al-Anbiya
Al-Hajj
Al-Mu'minun
An-Nur
Al-Furqan
Asy-Syu'ara'
An-Naml
Al-Qasas
Al-'Ankabut
Ar-Rum
Luqman
As-Sajdah
Al-Ahzab
Saba'
Fatir
Ya Sin
As-Saffat
Sad
Az-Zumar
Ghafir
Fussilat
Asy-Syura
Az-Zukhruf
Ad-Dukhan
Al-Jasiyah
Al-Ahqaf
Muhammad
Al-Fath
Al-Hujurat
Qaf
Az-Zariyat
At-Tur
An-Najm
Al-Qamar
Ar-Rahman
Al-Waqi'ah
Al-Hadid
Al-Mujadilah
Al-Hasyr
Al-Mumtahanah
As-Saff
Al-Jumu'ah
Al-Munafiqun
At-Tagabun
At-Talaq
At Tahriim
Al-Mulk
Al-Qalam
Al-Haqqah
Al-Ma'arij
Nuh
Al-Jinn
Al-Muzzammil
Al-Muddassir
Al-Qiyamah
Al-Insan
Al-Mursalat
An-Naba'
An-Nazi'at
'Abasa
At-Takwir
Al-Infitar
Al-Tatfif
Al-Insyiqaq
Al-Buruj
At-Tariq
Al-A'la
Al-Gasyiyah
Al-Faj
Al-Balad
Asy-Syams
Al-Lail
Ad-Duha
Al-Insyirah
At-Tin
Al-'Alaq
Al-Qadr
Al-Bayyinah
Az-Zalzalah
Al-'Adiyat
Al-Qari'ah
At-Takasur
Al-'Asr
Al-Humazah
Al-Fil
Quraisy
Al-Ma'un
Al-Kausar
Al-Kafirun
An-Nasr
Al-Lahab
Al-Ikhlas
Al-Falaq
An-Nas)=====";

//------------------------------------------------------------------------------------------

//------------------------------------------------------------------------------------------

char jumlahayat[] PROGMEM = R"=====(7
286
200
176
120
165
206
75
129
109
123
111
43
52
99
128
111
110
98
135
112
78
118
64
77
227
93
88
69
60
34
30
73
54
45
83
182
88
75
85
54
53
89
59
37
35
38
29
18
45
60
49
62
55
78
96
29
22
24
13
14
11
11
18
12
12
30
52
52
44
28
28
20
56
40
31
50
40
46
42
29
19
36
25
22
17
19
26
30
20
15
21
11
8
8
19
5
8
8
11
11
8
3
9
5
4
7
3
6
3
5
4
5
6)=====";

//------------------------------------------------------------------------------------------

//------------------------------------------------------------------------------------------

char databaseKoordinat[] PROGMEM = R"=====(KAB. ACEH BARAT
KAB. ACEH BARAT DAYA
KAB. ACEH BESAR
KAB. ACEH JAYA
KAB. ACEH SELATAN
KAB. ACEH SINGKIL
KAB. ACEH TAMIANG
KAB. ACEH TENGAH
KAB. ACEH TENGGARA
KAB. ACEH TIMUR
KAB. ACEH UTARA
KAB. BENER MERIAH
KAB. BIREUEN
KAB. GAYO LUES
KAB. NAGAN RAYA
KAB. PIDIE
KAB. PIDIE JAYA
KAB. SIMEULUE
KOTA BANDA ACEH
KOTA LANGSA
KOTA LHOKSEUMAWE
KOTA SABANG
KOTA SUBULUSSALAM
KAB. ASAHAN
KAB. BATUBARA
KAB. DAIRI
KAB. DELI SERDANG
KAB. HUMBANG HASUNDUTAN
KAB. KARO
KAB. LABUHANBATU
KAB. LABUHANBATU SELATAN
KAB. LABUHANBATU UTARA
KAB. LANGKAT
KAB. MANDAILING NATAL
KAB. NIAS
KAB. NIAS BARAT
KAB. NIAS SELATAN
KAB. NIAS UTARA
KAB. PADANG LAWAS
KAB. PADANG LAWAS UTARA
KAB. PAKPAK BHARAT
KAB. SAMOSIR
KAB. SERDANG BEDAGAI
KAB. SIMALUNGUN
KAB. TAPANULI SELATAN
KAB. TAPANULI TENGAH
KAB. TAPANULI UTARA
KAB. TOBA SAMOSIR
KOTA BINJAI
KOTA GUNUNGSITOLI
KOTA MEDAN
KOTA PADANGSIDEMPUAN
KOTA PEMATANGSIANTAR
KOTA SIBOLGA
KOTA TANJUNGBALAI
KOTA TEBING TINGGI
KAB. AGAM
KAB. DHARMASRAYA
KAB. KEPULAUAN MENTAWAI
KAB. LIMA PULUH KOTA
KAB. PADANG PARIAMAN
KAB. PASAMAN
KAB. PASAMAN BARAT
KAB. PESISIR SELATAN
KAB. SIJUNJUNG
KAB. SOLOK
KAB. SOLOK SELATAN
KAB. TANAH DATAR
KOTA BUKITTINGGI
KOTA PADANG
KOTA PADANGPANJANG
KOTA PARIAMAN
KOTA PAYAKUMBUH
KOTA SAWAHLUNTO
KOTA SOLOK
KAB. BENGKALIS
KAB. INDRAGIRI HILIR
KAB. INDRAGIRI HULU
KAB. KAMPAR
KAB. KEPULAUAN MERANTI
KAB. KUANTAN SINGINGI
KAB. PELALAWAN
KAB. ROKAN HILIR
KAB. ROKAN HULU
KAB. SIAK
KOTA DUMAI
KOTA PEKANBARU
KAB. BINTAN
KAB. KARIMUN
KAB. KEPULAUAN ANAMBAS
KAB. LINGGA
KAB. NATUNA
KOTA BATAM
KOTA TANJUNG PINANG
PULAU TAMBELAN KAB. BINTAN
PEKAJANG KAB. LINGGA
PULAU SERASAN KAB. NATUNA
PULAU MIDAI KAB. NATUNA
PULAU LAUT KAB. NATUNA
KAB. BATANGHARI
KAB. BUNGO
KAB. KERINCI
KAB. MERANGIN
KAB. MUARO JAMBI
KAB. SAROLANGUN
KAB. TANJUNG JABUNG BARAT
KAB. TANJUNG JABUNG TIMUR
KAB. TEBO
KOTA JAMBI
KOTA SUNGAI PENUH
KAB. BENGKULU SELATAN
KAB. BENGKULU TENGAH
KAB. BENGKULU UTARA
KAB. KAUR
KAB. KEPAHIANG
KAB. LEBONG
KAB. MUKOMUKO
KAB. REJANG LEBONG
KAB. SELUMA
KOTA BENGKULU
KAB. BANYUASIN
KAB. EMPAT LAWANG
KAB. LAHAT
KAB. MUARA ENIM
KAB. MUSI BANYUASIN
KAB. MUSI RAWAS
KAB. MUSI RAWAS UTARA
KAB. OGAN ILIR
KAB. OGAN KOMERING ILIR
KAB. OGAN KOMERING ULU
KAB. OGAN KOMERING ULU SELATAN
KAB. OGAN KOMERING ULU TIMUR
KAB. PENUKAL ABAB LEMATANG ILIR
KOTA LUBUKLINGGAU
KOTA PAGAR ALAM
KOTA PALEMBANG
KOTA PRABUMULIH
KAB. BANGKA
KAB. BANGKA BARAT
KAB. BANGKA SELATAN
KAB. BANGKA TENGAH
KAB. BELITUNG
KAB. BELITUNG TIMUR
KOTA PANGKAL PINANG
KAB. LAMPUNG TENGAH
KAB. LAMPUNG UTARA
KAB. LAMPUNG SELATAN
KAB. LAMPUNG BARAT
KAB. LAMPUNG TIMUR
KAB. MESUJI
KAB. PESAWARAN
KAB. PESISIR BARAT
KAB. PRINGSEWU
KAB. TULANG BAWANG
KAB. TULANG BAWANG BARAT
KAB. TANGGAMUS
KAB. WAY KANAN
KOTA BANDAR LAMPUNG
KOTA METRO
KAB. LEBAK
KAB. PANDEGLANG
KAB. SERANG
KAB. TANGERANG
KOTA CILEGON
KOTA SERANG
KOTA TANGERANG
KOTA TANGERANG SELATAN
KAB. BANDUNG
KAB. BANDUNG BARAT
KAB. BEKASI
KAB. BOGOR
KAB. CIAMIS
KAB. CIANJUR
KAB. CIREBON
KAB. GARUT
KAB. INDRAMAYU
KAB. KARAWANG
KAB. KUNINGAN
KAB. MAJALENGKA
KAB. PANGANDARAN
KAB. PURWAKARTA
KAB. SUBANG
KAB. SUKABUMI
KAB. SUMEDANG
KAB. TASIKMALAYA
KOTA BANDUNG
KOTA BANJAR
KOTA BEKASI
KOTA BOGOR
KOTA CIMAHI
KOTA CIREBON
KOTA DEPOK
KOTA SUKABUMI
KOTA TASIKMALAYA
KOTA JAKARTA
KAB. ADMINISTRASI KEPULAUAN SERIBU
KAB. BANJARNEGARA
KAB. BANYUMAS
KAB. BATANG
KAB. BLORA
KAB. BOYOLALI
KAB. BREBES
KAB. CILACAP
KAB. DEMAK
KAB. GROBOGAN
KAB. JEPARA
KAB. KARANGANYAR
KAB. KEBUMEN
KAB. KENDAL
KAB. KLATEN
KAB. KUDUS
KAB. MAGELANG
KAB. PATI
KAB. PEKALONGAN
KAB. PEMALANG
KAB. PURBALINGGA
KAB. PURWOREJO
KAB. REMBANG
KAB. SEMARANG
KAB. SRAGEN
KAB. SUKOHARJO
KAB. TEGAL
KAB. TEMANGGUNG
KAB. WONOGIRI
KAB. WONOSOBO
KOTA MAGELANG
KOTA PEKALONGAN
KOTA SALATIGA
KOTA SEMARANG
KOTA SURAKARTA
KOTA TEGAL
KAB. BANTUL
KAB. GUNUNGKIDUL
KAB. KULON PROGO
KAB. SLEMAN
KOTA YOGYAKARTA
KAB. BANGKALAN
KAB. BANYUWANGI
KAB. BLITAR
KAB. BOJONEGORO
KAB. BONDOWOSO
KAB. GRESIK
KAB. JEMBER
KAB. JOMBANG
KAB. KEDIRI
KAB. LAMONGAN
KAB. LUMAJANG
KAB. MADIUN
KAB. MAGETAN
KAB. MALANG
KAB. MOJOKERTO
KAB. NGANJUK
KAB. NGAWI
KAB. PACITAN
KAB. PAMEKASAN
KAB. PASURUAN
KAB. PONOROGO
KAB. PROBOLINGGO
KAB. SAMPANG
KAB. SIDOARJO
KAB. SITUBONDO
KAB. SUMENEP
KAB. TRENGGALEK
KAB. TUBAN
KAB. TULUNGAGUNG
KOTA BATU
KOTA BLITAR
KOTA KEDIRI
KOTA MADIUN
KOTA MALANG
KOTA MOJOKERTO
KOTA PASURUAN
KOTA PROBOLINGGO
KOTA SURABAYA
KAB. BADUNG
KAB. BANGLI
KAB. BULELENG
KAB. GIANYAR
KAB. JEMBRANA
KAB. KARANGASEM
KAB. KLUNGKUNG
KAB. TABANAN
KOTA DENPASAR
KAB. BIMA
KAB. DOMPU
KAB. LOMBOK BARAT
KAB. LOMBOK TENGAH
KAB. LOMBOK TIMUR
KAB. LOMBOK UTARA
KAB. SUMBAWA
KAB. SUMBAWA BARAT
KOTA BIMA
KOTA MATARAM
KAB. ALOR
KAB. BELU
KAB. ENDE
KAB. FLORES TIMUR
KAB. KUPANG
KAB. LEMBATA
KAB. MALAKA
KAB. MANGGARAI
KAB. MANGGARAI BARAT
KAB. MANGGARAI TIMUR
KAB. NGADA
KAB. NAGEKEO
KAB. ROTE NDAO
KAB. SABU RAIJUA
KAB. SIKKA
KAB. SUMBA BARAT
KAB. SUMBA BARAT DAYA
KAB. SUMBA TENGAH
KAB. SUMBA TIMUR
KAB. TIMOR TENGAH SELATAN
KAB. TIMOR TENGAH UTARA
KOTA KUPANG
KAB. BENGKAYANG
KAB. KAPUAS HULU
KAB. KAYONG UTARA
KAB. KETAPANG
KAB. KUBU RAYA
KAB. LANDAK
KAB. MELAWI
KAB. MEMPAWAH
KAB. SAMBAS
KAB. SANGGAU
KAB. SEKADAU
KAB. SINTANG
KOTA PONTIANAK
KOTA SINGKAWANG
KAB. BALANGAN
KAB. BANJAR
KAB. BARITO KUALA
KAB. HULU SUNGAI SELATAN
KAB. HULU SUNGAI TENGAH
KAB. HULU SUNGAI UTARA
KAB. KOTABARU
KAB. TABALONG
KAB. TANAH BUMBU
KAB. TANAH LAUT
KAB. TAPIN
KOTA BANJARBARU
KOTA BANJARMASIN
KAB. BARITO SELATAN
KAB. BARITO TIMUR
KAB. BARITO UTARA
KAB. GUNUNG MAS
KAB. KAPUAS
KAB. KATINGAN
KAB. KOTAWARINGIN BARAT
KAB. KOTAWARINGIN TIMUR
KAB. LAMANDAU
KAB. MURUNG RAYA
KAB. PULANG PISAU
KAB. SUKAMARA
KAB. SERUYAN
KOTA PALANGKARAYA
KAB. BERAU
KAB. KUTAI BARAT
KAB. KUTAI KARTANEGARA
KAB. KUTAI TIMUR
KAB. MAHAKAM ULU
KAB. PASER
KAB. PENAJAM PASER UTARA
KOTA BALIKPAPAN
KOTA BONTANG
KOTA SAMARINDA
KAB. BULUNGAN
KAB. MALINAU
KAB. NUNUKAN
KAB. TANA TIDUNG
KOTA TARAKAN
KAB. BOALEMO
KAB. BONE BOLANGO
KAB. GORONTALO
KAB. GORONTALO UTARA
KAB. POHUWATO
KOTA GORONTALO
KAB. BANTAENG
KAB. BARRU
KAB. BONE
KAB. BULUKUMBA
KAB. ENREKANG
KAB. GOWA
KAB. JENEPONTO
KAB. KEPULAUAN SELAYAR
KAB. LUWU
KAB. LUWU TIMUR
KAB. LUWU UTARA
KAB. MAROS
KAB. PANGKAJENE DAN KEPULAUAN
KAB. PINRANG
KAB. SIDENRENG RAPPANG
KAB. SINJAI
KAB. SOPPENG
KAB. TAKALAR
KAB. TANA TORAJA
KAB. TORAJA UTARA
KAB. WAJO
KOTA MAKASSAR
KOTA PALOPO
KOTA PAREPARE
KAB. BOMBANA
KAB. BUTON
KAB. BUTON SELATAN
KAB. BUTON TENGAH
KAB. BUTON UTARA
KAB. KOLAKA
KAB. KOLAKA TIMUR
KAB. KOLAKA UTARA
KAB. KONAWE
KAB. KONAWE KEPULAUAN
KAB. KONAWE SELATAN
KAB. KONAWE UTARA
KAB. MUNA
KAB. MUNA BARAT
KAB. WAKATOBI
KOTA BAU-BAU
KOTA KENDARI
KAB. BANGGAI
KAB. BANGGAI KEPULAUAN
KAB. BANGGAI LAUT
KAB. BUOL
KAB. DONGGALA
KAB. MOROWALI
KAB. MOROWALI UTARA
KAB. PARIGI MOUTONG
KAB. POSO
KAB. SIGI
KAB. TOJO UNA-UNA
KAB. TOLI-TOLI
KOTA PALU
KAB. BOLAANG MONGONDOW
KAB. BOLAANG MONGONDOW SELATAN
KAB. BOLAANG MONGONDOW TIMUR
KAB. BOLAANG MONGONDOW UTARA
KAB. KEPULAUAN SANGIHE
KAB. KEPULAUAN SIAU TAGULANDANG BIARO
KAB. KEPULAUAN TALAUD
KAB. MINAHASA
KAB. MINAHASA SELATAN
KAB. MINAHASA TENGGARA
KAB. MINAHASA UTARA
KOTA BITUNG
KOTA KOTAMOBAGU
KOTA MANADO
KOTA TOMOHON
KAB. MAJENE
KAB. MAMASA
KAB. MAMUJU
KAB. MAMUJU TENGAH
KAB. MAMUJU UTARA
KAB. POLEWALI MANDAR
KAB. BURU
KAB. BURU SELATAN
KAB. KEPULAUAN ARU
KAB. MALUKU BARAT DAYA
KAB. MALUKU TENGAH
KAB. MALUKU TENGGARA
KAB. MALUKU TENGGARA BARAT
KAB. SERAM BAGIAN BARAT
KAB. SERAM BAGIAN TIMUR
KOTA AMBON
KOTA TUAL
KAB. HALMAHERA BARAT
KAB. HALMAHERA TENGAH
KAB. HALMAHERA UTARA
KAB. HALMAHERA SELATAN
KAB. KEPULAUAN SULA
KAB. HALMAHERA TIMUR
KAB. PULAU MOROTAI
KAB. PULAU TALIABU
KOTA TERNATE
KOTA TIDORE KEPULAUAN
KAB. ASMAT
KAB. BIAK NUMFOR
KAB. BOVEN DIGOEL
KAB. DEIYAI
KAB. DOGIYAI
KAB. INTAN JAYA
KAB. JAYAPURA
KAB. JAYAWIJAYA
KAB. KEEROM
KAB. KEPULAUAN YAPEN
KAB. LANNY JAYA
KAB. MAMBERAMO RAYA
KAB. MAMBERAMO TENGAH
KAB. MAPPI
KAB. MERAUKE
KAB. MIMIKA
KAB. NABIRE
KAB. NDUGA
KAB. PANIAI
KAB. PEGUNUNGAN BINTANG
KAB. PUNCAK
KAB. PUNCAK JAYA
KAB. SARMI
KAB. SUPIORI
KAB. TOLIKARA
KAB. WAROPEN
KAB. YAHUKIMO
KAB. YALIMO
KOTA JAYAPURA
KAB. YAPEN WAROPEN
KAB. FAKFAK
KAB. KAIMANA
KAB. MANOKWARI
KAB. MANOKWARI SELATAN
KAB. MAYBRAT
KAB. PEGUNUNGAN ARFAK
KAB. RAJA AMPAT
KAB. SORONG
KAB. SORONG SELATAN
KAB. TAMBRAUW
KAB. TELUK BINTUNI
KAB. TELUK WONDAMA
KOTA SORONG)=====";

//------------------------------------------------------------------------------------------

//var content = "Al Fatihah\nAl Baqarah\nAli Imran\nAn Nisa\nAl Ma'idah\nAl An'am\nAl-A'raf\nAl-Anfal\nAt-Taubah\nYunus\nHud\nYusuf\nAr-Ra'd\nIbrahim\nAl-Hijr\nAn-Nahl\nAl-Isra'\nAl-Kahf\nMaryam\nTa Ha\nAl-Anbiya\nAl-Hajj\nAl-Mu'minun\nAn-Nur\nAl-Furqan\nAsy-Syu'ara'\nAn-Naml\nAl-Qasas\nAl-'Ankabut\nAr-Rum\nLuqman\nAs-Sajdah\nAl-Ahzab\nSaba'\nFatir\nYa Sin\nAs-Saffat\nSad\nAz-Zumar\nGhafir\nFussilat\nAsy-Syura\nAz-Zukhruf\nAd-Dukhan\nAl-Jasiyah\nAl-Ahqaf\nMuhammad\nAl-Fath\nAl-Hujurat\nQaf\nAz-Zariyat\nAt-Tur\nAn-Najm\nAl-Qamar\nAr-Rahman\nAl-Waqi'ah\nAl-Hadid\nAl-Mujadilah\nAl-Hasyr\nAl-Mumtahanah\nAs-Saff\nAl-Jumu'ah\nAl-Munafiqun\nAt-Tagabun\nAt-Talaq\nAt Tahriim\nAl-Mulk\nAl-Qalam\nAl-Haqqah\nAl-Ma'arij\nNuh\nAl-Jinn\nAl-Muzzammil\nAl-Muddassir\nAl-Qiyamah\nAl-Insan\nAl-Mursalat\nAn-Naba'\nAn-Nazi'at\n'Abasa\nAt-Takwir\nAl-Infitar\nAl-Tatfif\nAl-Insyiqaq\nAl-Buruj\nAt-Tariq\nAl-A'la\nAl-Gasyiyah\nAl-Faj\nAl-Balad\nAsy-Syams\nAl-Lail\nAd-Duha\nAl-Insyirah\nAt-Tin\nAl-'Alaq\nAl-Qadr\nAl-Bayyinah\nAz-Zalzalah\nAl-'Adiyat\nAl-Qari'ah\nAt-Takasur\nAl-'Asr\nAl-Humazah\nAl-Fil\nQuraisy\nAl-Ma'un\nAl-Kausar\nAl-Kafirun\nAn-Nasr\nAl-Lahab\nAl-Ikhlas\nAl-Falaq\nAn-Nas";
//var content2 = "3\n1\n3\n15\n1\n10\n0\n10";
//var content3 = "7\n286\n200\n176\n120\n165\n206\n75\n129\n109\n123\n111\n43\n52\n99\n128\n111\n110\n98\n135\n112\n78\n118\n64\n77\n227\n93\n88\n69\n60\n34\n30\n73\n54\n45\n83\n182\n88\n75\n85\n54\n53\n89\n59\n37\n35\n38\n29\n18\n45\n60\n49\n62\n55\n78\n96\n29\n22\n24\n13\n14\n11\n11\n18\n12\n12\n30\n52\n52\n44\n28\n28\n20\n56\n40\n31\n50\n40\n46\n42\n29\n19\n36\n25\n22\n17\n19\n26\n30\n20\n15\n21\n11\n8\n8\n19\n5\n8\n8\n11\n11\n8\n3\n9\n5\n4\n7\n3\n6\n3\n5\n4\n5\n6";
